/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fee_managment;

/**
 *
 * @author dsown
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_add_fees = new javax.swing.JButton();
        btn_search_rec = new javax.swing.JButton();
        btn_view_courses = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_view_report = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_about = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(28, 48, 89));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Lao Sangam MN", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tuition Fees Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(348, 348, 348))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, -1));

        btn_add_fees.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_add_fees.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/add.png")); // NOI18N
        btn_add_fees.setText(" Add Fees");
        btn_add_fees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_feesMouseClicked(evt);
            }
        });
        btn_add_fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_feesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 195, 91));

        btn_search_rec.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_search_rec.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/search.png")); // NOI18N
        btn_search_rec.setText("View Records");
        btn_search_rec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recMouseClicked(evt);
            }
        });
        btn_search_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_recActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search_rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 195, 91));

        btn_view_courses.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_view_courses.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/file.png")); // NOI18N
        btn_view_courses.setText(" Course List");
        btn_view_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_coursesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 411, 195, 91));

        btn_edit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/edit.png")); // NOI18N
        btn_edit.setText("Edit Course");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 411, 195, 91));

        btn_view_report.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_view_report.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/search (1).png")); // NOI18N
        btn_view_report.setText(" View Reports");
        btn_view_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_reportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 411, 195, 91));

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/turn-off.png")); // NOI18N
        btn_logout.setText(" Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 169, 59));

        btn_about.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_about.setIcon(new javax.swing.ImageIcon("/Users/dsown/Desktop/INS3035_JAVA/Tuitionfeemngm/Favicon/follower.png")); // NOI18N
        btn_about.setText(" About");
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 169, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_feesActionPerformed
        Add_Fees addFees=new Add_Fees();
        addFees.show();
        this.dispose();
    }//GEN-LAST:event_btn_add_feesActionPerformed

    private void btn_search_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_recActionPerformed
        Search_Record search=new Search_Record();
        search.show();
        this.dispose();
    }//GEN-LAST:event_btn_search_recActionPerformed

    private void btn_view_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_coursesActionPerformed
        View_Courses course=new View_Courses();
        course.show();
        this.dispose();
    }//GEN-LAST:event_btn_view_coursesActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        Edit_Course edit=new Edit_Course();
        edit.show();
        this.dispose();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_view_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_reportActionPerformed
        View_Reports report=new View_Reports();
        report.show();
        this.dispose();
    }//GEN-LAST:event_btn_view_reportActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        Login_Page logout=new Login_Page();
        logout.show();
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        About about=new About();
        about.show();
        this.dispose();
    }//GEN-LAST:event_btn_aboutActionPerformed

    private void btn_add_feesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_feesMouseClicked
        Add_Fees addFees = new Add_Fees();
        addFees.setVisiable(true);
        this.dispose();
    }//GEN-LAST:event_btn_add_feesMouseClicked

    private void btn_search_recMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recMouseClicked
        Search_Record search = new Search_Record();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_search_recMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_add_fees;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_search_rec;
    private javax.swing.JButton btn_view_courses;
    private javax.swing.JButton btn_view_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
